import "./globals.css";
import { bodoni, josefin } from "@/ui/fonts";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { AuthProvider } from "@/context/AuthContext";
import { CommentRefreshProvider } from "@/components/context/CommentRefreshContext";
import { CartProvider } from "@/components/context/CartContext";



export const metadata = {
  title: "Jade",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bodoni.variable} ${josefin.variable}`}>
        <AuthProvider>
          <CartProvider>
            <CommentRefreshProvider>
            <Header/>
              <main>
                {children}
              </main>
            <Footer />
          </CommentRefreshProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
